/**
 * ============================================================
 *  ERASER TRAIL HOOK - Excalidraw-compatible animated eraser
 * ============================================================
 *
 *  This file contains ALL logic for the eraser's animated ribbon
 *  trail (the fluid stroke that streams behind the cursor while
 *  erasing). It is a faithful port of Excalidraw's EraserTrail
 *  + AnimatedTrail + LaserPointer, kept separate so that it
 *  cannot be accidentally edited or removed when working on
 *  other parts of DrawSurface.
 *
 *  WHAT THIS FILE DOES:
 *  - Manages the trail's point buffer (state + ref).
 *  - Feeds new points with Excalidraw's streamline (0.2).
 *  - Runs a requestAnimationFrame loop that prunes dead points
 *    and keeps the ribbon visually alive while the sweep is down.
 *  - Exposes a clearTrail() for instant vanish on release/leave.
 *
 *  CONSTANTS (Excalidraw's exact values):
 *  - TRAIL_DECAY = 200 ms  (DECAY_TIME: how long a point stays wide)
 *  - TRAIL_LENGTH = 10     (DECAY_LENGTH: points that get the length taper)
 *
 *  EXCALIDRAW REFERENCE:
 *  - excamaster/packages/laser-pointer/src/state.ts   (LaserPointer)
 *  - excamaster/packages/excalidraw/eraser/index.ts   (EraserTrail)
 *  - excamaster/packages/excalidraw/animatedTrail.ts   (AnimatedTrail)
 *
 *  DO NOT EDIT THIS FILE without understanding the Excalidraw
 *  eraser trail algorithm. If you need to change the visual
 *  appearance, adjust the constants below or the trailOutline
 *  function in engine/laser-trail.ts.
 * ============================================================
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { plerp } from "../engine/laser-trail";

/** How long a swept point stays alive - Excalidraw's DECAY_TIME. */
export const TRAIL_DECAY = 200;

/** How many points at the tail get the length taper - DECAY_LENGTH. */
export const TRAIL_LENGTH = 10;

/**
 * The eraser trail hook.
 *
 * @param drawingNowRef  A ref whose .current is true while the sweep is
 *                       pressed and moving. The hook reads it each frame
 *                       to decide whether to keep the loop alive (sweep)
 *                       or let it rest (hover / idle).
 * @param isEraserTool   True when the active tool is the eraser or the
 *                       eraser-pen. The hook uses this to auto-clear the
 *                       trail when the user switches away.
 */
export function useEraserTrail(
  drawingNowRef: React.MutableRefObject<boolean>,
  isEraserTool: boolean,
) {
  /** The current trail points - React state that triggers re-render. */
  const [eraserTrail, setEraserTrail] = useState<number[][]>([]);

  /** Mutable ref mirror of eraserTrail - avoids stale closures in the
   *  rAF loop. Always kept in sync with the state. */
  const eraserTrailRef = useRef<number[][]>([]);

  /** Handle for the running requestAnimationFrame. 0 = not scheduled. */
  const trailRaf = useRef(0);

  /** Whether the next pushed point begins the ribbon fresh (no
   *  streamline applied). Set to true on pointerdown, false after
   *  the first push. */
  const trailFresh = useRef(false);

  // ---------------------------------------------------------------
  //  The animation loop - Excalidraw's stepTrail.
  //
  //  While the sweep is down (drawingNowRef.current === true) the loop
  //  runs every frame: it prunes points older than TRAIL_DECAY ms
  //  that are also beyond the last TRAIL_LENGTH positions, so the
  //  ribbon melts off its own tail.
  //
  //  While hovering (drawingNowRef.current === false) the loop only
  //  runs while there are points to drain. Once nothing changes
  //  it stops and waits for the next push.
  // ---------------------------------------------------------------
  const stepTrail = useCallback(() => {
    trailRaf.current = 0;
    const now = performance.now();
    const pts = eraserTrailRef.current;
    if (pts.length === 0) return;

    if (drawingNowRef.current) {
      const len = pts.length;
      eraserTrailRef.current = pts.filter(
        (p, i) => now - p[2] < TRAIL_DECAY || len - i <= TRAIL_LENGTH,
      );
      setEraserTrail(eraserTrailRef.current);
      trailRaf.current = requestAnimationFrame(stepTrail);
      return;
    }

    const len = pts.length;
    const alive = pts.filter(
      (p, i) => now - p[2] < TRAIL_DECAY || len - i <= TRAIL_LENGTH,
    );
    if (alive.length !== pts.length) {
      eraserTrailRef.current = alive;
      setEraserTrail(alive);
      trailRaf.current = requestAnimationFrame(stepTrail);
    }
  }, [drawingNowRef]);

  // ---------------------------------------------------------------
  //  pushTrail - Excalidraw's addPoint.
  //
  //  Lay a point under the eraser's tip.  The first point of a
  //  sweep lands as-is; later ones are pulled toward the last by
  //  the streamline (0.8 blend = 1 - 0.2), and a point exactly
  //  where one already sits is ignored.
  //
  //  IMPORTANT: plerp returns [x, y, r] but we only keep x and y.
  //  The timestamp (p[2]) is ALWAYS performance.now() so the
  //  decay calculation in stepTrail / the render block works
  //  correctly.  (An earlier bug spread plerp's 3 values +
  //  timestamp into a 4-element array, making p[2] the lerped
  //  pressure instead of the timestamp - the ribbon was invisible.)
  // ---------------------------------------------------------------
  const pushTrail = useCallback(
    (x: number, y: number) => {
      const pts = eraserTrailRef.current;
      const last = pts[pts.length - 1];
      if (last && last[0] === x && last[1] === y) return;

      const pt: number[] = !last || trailFresh.current
        ? [x, y, performance.now()]
        : (() => {
            const [lx, ly] = plerp(
              [last[0], last[1], 0],
              [x, y, 0],
              0.8,
            );
            return [lx, ly, performance.now()];
          })();

      trailFresh.current = false;
      eraserTrailRef.current = [...pts, pt];
      setEraserTrail(eraserTrailRef.current);
      if (!trailRaf.current) {
        trailRaf.current = requestAnimationFrame(stepTrail);
      }
    },
    [stepTrail],
  );

  // ---------------------------------------------------------------
  //  clearTrail - Excalidraw's endPath + clearTrails.
  //
  //  Instantly removes the entire ribbon.  Called on:
  //  - pointer release (finishGesture)
  //  - pointer leaving the SVG (onPointerLeave)
  //  - tool switching away from eraser (tool-change effect below)
  // ---------------------------------------------------------------
  const clearTrail = useCallback(() => {
    if (trailRaf.current) cancelAnimationFrame(trailRaf.current);
    trailRaf.current = 0;
    eraserTrailRef.current = [];
    setEraserTrail([]);
  }, []);

  // ---------------------------------------------------------------
  //  Cleanup effects
  // ---------------------------------------------------------------

  // Kill the rAF loop when the component unmounts.
  useEffect(() => () => clearTrail(), [clearTrail]);

  // Clear the trail when the user switches away from the eraser.
  useEffect(() => {
    if (isEraserTool) return;
    clearTrail();
  }, [isEraserTool, clearTrail]);

  // ---------------------------------------------------------------
  //  startSweep - called from onPointerDown when the eraser begins.
  //  Arms the trailFresh flag so the first push lands un-streamlined.
  // ---------------------------------------------------------------
  const startSweep = useCallback(() => {
    trailFresh.current = true;
  }, []);

  return {
    /** The current trail points - pass to the render block. */
    eraserTrail,
    /** Feed a point under the cursor. */
    pushTrail,
    /** Instantly clear the ribbon. */
    clearTrail,
    /** Arm the fresh flag for the next push (call on pointerdown). */
    startSweep,
  } as const;
}
